# See https://pre-commit.com/ for usage and config
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:

  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:

  - id: check-added-large-files
    name: Check for added large files
    stages: [commit]
    entry: check-added-large-files
    language: system

  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort src
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black src
    types: [python]

  - id: ruff
    name: ruff
    stages: [commit]
    language: system
    entry: poetry run ruff src
    types: [python]

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: poetry run mypy
    types: [python]
    require_serial: true

  - id: darglint
    name: darglint
    stages: [commit]
    language: system
    entry: poetry run darglint src
    types: [python]
    require_serial: true

  - id: pyupgrade
    name: pyupgrade
    stages: [commit]
    language: system
    entry: poetry run pyupgrade
    types: [python]
    require_serial: true

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: poetry run pytest tests
    types: [python]
    pass_filenames: false
