# See https://pre-commit.com/ for usage and config
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:

  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:

  - id: check-added-large-files
    name: Check for added large files
    stages: [commit]
    entry: check-added-large-files
    language: system

  - id: ruff_format
    name: ruff_format
    stages: [commit]
    language: system
    entry: poetry run ruff format src tests assets
    types: [python]

  - id: ruff
    name: ruff
    stages: [commit]
    language: system
    entry: poetry run ruff src tests assets
    types: [python]
    args: [ --fix, --exit-non-zero-on-fix ]

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: poetry run mypy
    types: [python]
    require_serial: true

  - id: darglint
    name: darglint
    stages: [commit]
    language: system
    entry: poetry run darglint src tests assets
    types: [python]
    require_serial: true

  - id: pydocstringformatter
    name: pydocstringformatter
    stages: [commit]
    language: system
    entry: poetry run pydocstringformatter src tests assets
    types: [python]

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: poetry run pytest tests
    types: [python]
    pass_filenames: false
