title: [Incoherent scatter spectrum model]
description: [Calculate incoherent scatter spectra using arbitrary isotropic electron velocity distributions]
theme: jekyll-theme-minimal
show_downloads: ["true"]
logo: /img/normal_is_spectra.png
